// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_tracks.sql

package sqlc

import (
	"context"
)

const getOrCreateAlbumTracks = `-- name: GetOrCreateAlbumTracks :exec
INSERT INTO album_tracks (album_id, track_id) VALUES (?, ?)
ON CONFLICT (album_id, track_id)
DO UPDATE SET album_id = album_id
RETURNING id, album_id, track_id
`

type GetOrCreateAlbumTracksParams struct {
	AlbumID string
	TrackID string
}

func (q *Queries) GetOrCreateAlbumTracks(ctx context.Context, arg GetOrCreateAlbumTracksParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateAlbumTracks, arg.AlbumID, arg.TrackID)
	return err
}
