// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_artists.sql

package sqlc

import (
	"context"
)

const getOrCreateAlbumArtist = `-- name: GetOrCreateAlbumArtist :exec
INSERT INTO album_artists (album_id, artist_id) VALUES (?, ?)
ON CONFLICT (album_id, artist_id)
DO UPDATE SET album_id = album_id
RETURNING id, album_id, artist_id
`

type GetOrCreateAlbumArtistParams struct {
	AlbumID  string
	ArtistID string
}

func (q *Queries) GetOrCreateAlbumArtist(ctx context.Context, arg GetOrCreateAlbumArtistParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateAlbumArtist, arg.AlbumID, arg.ArtistID)
	return err
}
