// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package sqlc

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :exec
INSERT INTO albums (id, spotify_id, title) VALUES (?, ?, ?)
`

type CreateAlbumParams struct {
	ID        string
	SpotifyID string
	Title     string
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, createAlbum, arg.ID, arg.SpotifyID, arg.Title)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, spotify_id, title, created_at, deleted_at FROM albums WHERE id = ?
`

func (q *Queries) GetAlbum(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlbumBySpotifyId = `-- name: GetAlbumBySpotifyId :one
SELECT id, spotify_id, title, created_at, deleted_at FROM albums WHERE spotify_id = ?
`

func (q *Queries) GetAlbumBySpotifyId(ctx context.Context, spotifyID string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbumBySpotifyId, spotifyID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrCreateAlbum = `-- name: GetOrCreateAlbum :exec
INSERT INTO albums (id, spotify_id, title) VALUES (?, ?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET spotify_id = spotify_id
RETURNING id, spotify_id, title, created_at, deleted_at
`

type GetOrCreateAlbumParams struct {
	ID        string
	SpotifyID string
	Title     string
}

func (q *Queries) GetOrCreateAlbum(ctx context.Context, arg GetOrCreateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateAlbum, arg.ID, arg.SpotifyID, arg.Title)
	return err
}
