// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package sqlc

import (
	"context"
)

const createArtist = `-- name: CreateArtist :exec
INSERT INTO artists (id, spotify_id, name) VALUES (?, ?, ?)
`

type CreateArtistParams struct {
	ID        string
	SpotifyID string
	Name      string
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) error {
	_, err := q.db.ExecContext(ctx, createArtist, arg.ID, arg.SpotifyID, arg.Name)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT id, spotify_id, name, created_at, deleted_at FROM artists WHERE id = ?
`

func (q *Queries) GetArtist(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArtistBySpotifyId = `-- name: GetArtistBySpotifyId :one
SELECT id, spotify_id, name, created_at, deleted_at FROM artists WHERE spotify_id = ?
`

func (q *Queries) GetArtistBySpotifyId(ctx context.Context, spotifyID string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistBySpotifyId, spotifyID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrCreateArtist = `-- name: GetOrCreateArtist :exec
INSERT INTO artists (id, spotify_id, name) VALUES (?, ?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET spotify_id = spotify_id
RETURNING id, spotify_id, name, created_at, deleted_at
`

type GetOrCreateArtistParams struct {
	ID        string
	SpotifyID string
	Name      string
}

func (q *Queries) GetOrCreateArtist(ctx context.Context, arg GetOrCreateArtistParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateArtist, arg.ID, arg.SpotifyID, arg.Name)
	return err
}
