// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package sqlc

import (
	"context"

	"shmoopicks/src/internal/core/db/models"
)

const createFeed = `-- name: CreateFeed :one
insert into feeds (user_id, kind)
values (?, ?)
returning id, user_id, kind, created_at, last_synced_at
`

type CreateFeedParams struct {
	UserID string
	Kind   models.FeedKind
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.UserID, arg.Kind)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const getFeedsByUserId = `-- name: GetFeedsByUserId :many
select id, user_id, kind, created_at, last_synced_at from feeds where user_id = ?
`

func (q *Queries) GetFeedsByUserId(ctx context.Context, userID string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleFeedsBatch = `-- name: GetStaleFeedsBatch :many
SELECT id, user_id, kind, created_at, last_synced_at FROM feeds
WHERE last_synced_at < datetime('now', ?)
OR last_synced_at IS NULL
ORDER BY last_synced_at ASC
LIMIT 10
`

func (q *Queries) GetStaleFeedsBatch(ctx context.Context, datetime interface{}) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getStaleFeedsBatch, datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds (id, user_id, kind)
VALUES (?, ?, ?)
ON CONFLICT (user_id, kind) DO UPDATE SET
    user_id = excluded.user_id,
    kind = excluded.kind
RETURNING id, user_id, kind, created_at, last_synced_at
`

type UpsertFeedParams struct {
	ID     string
	UserID string
	Kind   models.FeedKind
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed, arg.ID, arg.UserID, arg.Kind)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}
