// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"shmoopicks/src/internal/core/db/models"
)

type Album struct {
	ID        string
	SpotifyID string
	Title     string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type AlbumArtist struct {
	ID       string
	AlbumID  string
	ArtistID string
}

type AlbumTrack struct {
	ID      string
	AlbumID string
	TrackID string
}

type Artist struct {
	ID        string
	SpotifyID string
	Name      string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type Feed struct {
	ID           string
	UserID       string
	Kind         models.FeedKind
	CreatedAt    time.Time
	LastSyncedAt sql.NullTime
}

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Release struct {
	ID        string
	AlbumID   string
	Format    string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type Track struct {
	ID        string
	SpotifyID string
	Title     string
	AlbumID   string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID        string
	SpotifyID string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type UserArtist struct {
	ID        string
	UserID    string
	ArtistID  string
	AddedAt   time.Time
	DeletedAt sql.NullTime
}

type UserRelease struct {
	ID        string
	UserID    string
	ReleaseID string
	AddedAt   time.Time
	DeletedAt sql.NullTime
}

type UserTrack struct {
	ID        string
	UserID    string
	TrackID   string
	AddedAt   time.Time
	DeletedAt sql.NullTime
}
