// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package sqlc

import (
	"context"
)

const createRelease = `-- name: CreateRelease :exec
INSERT INTO releases (id, album_id, format) VALUES (?, ?, ?)
`

type CreateReleaseParams struct {
	ID      string
	AlbumID string
	Format  string
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) error {
	_, err := q.db.ExecContext(ctx, createRelease, arg.ID, arg.AlbumID, arg.Format)
	return err
}

const getOrCreateRelease = `-- name: GetOrCreateRelease :exec
INSERT INTO releases (id, album_id, format) VALUES (?, ?, ?)
ON CONFLICT (album_id, format)
DO UPDATE SET album_id = album_id
RETURNING id, album_id, format, created_at, deleted_at
`

type GetOrCreateReleaseParams struct {
	ID      string
	AlbumID string
	Format  string
}

func (q *Queries) GetOrCreateRelease(ctx context.Context, arg GetOrCreateReleaseParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateRelease, arg.ID, arg.AlbumID, arg.Format)
	return err
}

const getRelease = `-- name: GetRelease :one
SELECT id, album_id, format, created_at, deleted_at FROM releases WHERE id = ?
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Format,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReleases = `-- name: GetReleases :many
SELECT id, album_id, format, created_at, deleted_at FROM releases WHERE album_id = ?
`

func (q *Queries) GetReleases(ctx context.Context, albumID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getReleases, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Format,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :exec
UPDATE releases
SET
    album_id = COALESCE(?, album_id),
    format = COALESCE(?, format)
WHERE id = ?
`

type UpdateReleaseParams struct {
	AlbumID string
	Format  string
	ID      string
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) error {
	_, err := q.db.ExecContext(ctx, updateRelease, arg.AlbumID, arg.Format, arg.ID)
	return err
}
