// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package sqlc

import (
	"context"
)

const createTrack = `-- name: CreateTrack :exec
INSERT INTO tracks (id, spotify_id, title, album_id) VALUES (?, ?, ?, ?)
`

type CreateTrackParams struct {
	ID        string
	SpotifyID string
	Title     string
	AlbumID   string
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) error {
	_, err := q.db.ExecContext(ctx, createTrack,
		arg.ID,
		arg.SpotifyID,
		arg.Title,
		arg.AlbumID,
	)
	return err
}

const getOrCreateTrack = `-- name: GetOrCreateTrack :exec
INSERT INTO tracks (id, spotify_id, title, album_id) VALUES (?, ?, ?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET spotify_id = spotify_id
RETURNING id, spotify_id, title, album_id, created_at, deleted_at
`

type GetOrCreateTrackParams struct {
	ID        string
	SpotifyID string
	Title     string
	AlbumID   string
}

func (q *Queries) GetOrCreateTrack(ctx context.Context, arg GetOrCreateTrackParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateTrack,
		arg.ID,
		arg.SpotifyID,
		arg.Title,
		arg.AlbumID,
	)
	return err
}

const getTrack = `-- name: GetTrack :one
SELECT id, spotify_id, title, album_id, created_at, deleted_at FROM tracks WHERE id = ?
`

func (q *Queries) GetTrack(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.AlbumID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTrackBySpotifyId = `-- name: GetTrackBySpotifyId :one
SELECT id, spotify_id, title, album_id, created_at, deleted_at FROM tracks WHERE spotify_id = ?
`

func (q *Queries) GetTrackBySpotifyId(ctx context.Context, spotifyID string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackBySpotifyId, spotifyID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Title,
		&i.AlbumID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
