// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_releases.sql

package sqlc

import (
	"context"
	"time"
)

const getUserReleases = `-- name: GetUserReleases :many
SELECT user_releases.id, user_releases.user_id, user_releases.release_id, user_releases.added_at, user_releases.deleted_at, releases.id, releases.album_id, releases.format, releases.created_at, releases.deleted_at FROM user_releases
JOIN releases ON user_releases.release_id = releases.id
WHERE user_id = ?
`

type GetUserReleasesRow struct {
	UserRelease UserRelease
	Release     Release
}

func (q *Queries) GetUserReleases(ctx context.Context, userID string) ([]GetUserReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserReleases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReleasesRow
	for rows.Next() {
		var i GetUserReleasesRow
		if err := rows.Scan(
			&i.UserRelease.ID,
			&i.UserRelease.UserID,
			&i.UserRelease.ReleaseID,
			&i.UserRelease.AddedAt,
			&i.UserRelease.DeletedAt,
			&i.Release.ID,
			&i.Release.AlbumID,
			&i.Release.Format,
			&i.Release.CreatedAt,
			&i.Release.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserRelease = `-- name: UpsertUserRelease :one
INSERT INTO user_releases (id, user_id, release_id, added_at) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, release_id)
DO UPDATE SET added_at = COALESCE(EXCLUDED.added_at, added_at)
RETURNING id, user_id, release_id, added_at, deleted_at
`

type UpsertUserReleaseParams struct {
	ID        string
	UserID    string
	ReleaseID string
	AddedAt   time.Time
}

func (q *Queries) UpsertUserRelease(ctx context.Context, arg UpsertUserReleaseParams) (UserRelease, error) {
	row := q.db.QueryRowContext(ctx, upsertUserRelease,
		arg.ID,
		arg.UserID,
		arg.ReleaseID,
		arg.AddedAt,
	)
	var i UserRelease
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReleaseID,
		&i.AddedAt,
		&i.DeletedAt,
	)
	return i, err
}
