// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, spotify_id) VALUES (?, ?)
`

type CreateUserParams struct {
	ID        string
	SpotifyID string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.SpotifyID)
	return err
}

const getOrCreateUser = `-- name: GetOrCreateUser :exec
INSERT INTO users (id, spotify_id) VALUES (?, ?)
ON CONFLICT (spotify_id)
DO UPDATE SET spotify_id = spotify_id
RETURNING id, spotify_id, created_at, deleted_at
`

type GetOrCreateUserParams struct {
	ID        string
	SpotifyID string
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateUser, arg.ID, arg.SpotifyID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, spotify_id, created_at, deleted_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserBySpotifyId = `-- name: GetUserBySpotifyId :one
SELECT id, spotify_id, created_at, deleted_at FROM users WHERE spotify_id = ?
`

func (q *Queries) GetUserBySpotifyId(ctx context.Context, spotifyID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySpotifyId, spotifyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
