// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tracks.sql

package sqlc

import (
	"context"
)

const getOrCreateUserTrack = `-- name: GetOrCreateUserTrack :exec
INSERT INTO user_tracks (user_id, track_id) VALUES (?, ?)
ON CONFLICT (user_id, track_id)
DO UPDATE SET user_id = user_id
RETURNING id, user_id, track_id, added_at, deleted_at
`

type GetOrCreateUserTrackParams struct {
	UserID  string
	TrackID string
}

func (q *Queries) GetOrCreateUserTrack(ctx context.Context, arg GetOrCreateUserTrackParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateUserTrack, arg.UserID, arg.TrackID)
	return err
}
