// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_artists.sql

package sqlc

import (
	"context"
)

const getOrCreateUserArtist = `-- name: GetOrCreateUserArtist :exec
INSERT INTO user_artists (user_id, artist_id) VALUES (?, ?)
ON CONFLICT (user_id, artist_id)
DO UPDATE SET user_id = user_id
RETURNING id, user_id, artist_id, added_at, deleted_at
`

type GetOrCreateUserArtistParams struct {
	UserID   string
	ArtistID string
}

func (q *Queries) GetOrCreateUserArtist(ctx context.Context, arg GetOrCreateUserArtistParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateUserArtist, arg.UserID, arg.ArtistID)
	return err
}
