// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_releases.sql

package sqlc

import (
	"context"
)

const getOrCreateUserRelease = `-- name: GetOrCreateUserRelease :exec
INSERT INTO user_releases (user_id, release_id) VALUES (?, ?)
ON CONFLICT (user_id, release_id)
DO UPDATE SET user_id = user_id
RETURNING id, user_id, release_id, added_at, deleted_at
`

type GetOrCreateUserReleaseParams struct {
	UserID    string
	ReleaseID string
}

func (q *Queries) GetOrCreateUserRelease(ctx context.Context, arg GetOrCreateUserReleaseParams) error {
	_, err := q.db.ExecContext(ctx, getOrCreateUserRelease, arg.UserID, arg.ReleaseID)
	return err
}
